polymod/format/ParseRules.hx
polymod/util/Util.hx

This way, you can add specific rules for specific files like:
```haxe
var specificRule:CSVParseFormat = new CSVParseFormat(";", false);
parseRules.addFile("data/myspecificfile.csv", specificRule);
```

Add ability to create parse rules for specific files

---

polymod/backends/IBackend.hx
polymod/backends/LimeBackend.hx
polymod/backends/PolymodAssetLibrary.hx
polymod/backends/PolymodAssets.hx
polymod/backends/StubBackend.hx

Only implemented in Lime/OpenFL. Other backends will get null and an empty array respectively.

Added PolymodAssets.getPath() and PolymodAssets.list()

---

polymod/Polymod.hx
polymod/backends/HEAPSBackend.hx
polymod/backends/IBackend.hx
polymod/backends/LimeBackend.hx
polymod/backends/NMEBackend.hx
polymod/backends/PolymodAssets.hx
polymod/backends/StubBackend.hx

Until this is merged, people building Friday Night Funkin' (vanilla), Kade Engine, or most mods from source will experience a Null Object Reference crash upon entering the title screen.
This bug is caused by the fact that Polymod now checks for an `assetLibraryPaths` attribute in the `frameworkParams` the user passes to the init function. However, if `frameworkParams` itself is completely unspecified, attempting to access `frameworkParams.assetLibraryPaths` will throw a Null Object Reference and crash the program.
Until this change is deployed, you can run the following in your command line before rebuilding the game to apply the fix:
```
haxelib remove polymod
haxelib git polymod https://github.com/MasterEric/polymod
```

[CRITICAL BUG FIX] Resolve null object reference.

---

polymod/Polymod.hx
polymod/backends/PolymodAssetLibrary.hx

Very tiny PR, adds a log call before loading the mod, after loading the mod, or if the mod fails to load.
Useful because I wanted to print to the log for each mod that loads and whether they succeeded or failed.

Call the 'onError' callback before and after loading a mod.

---

README.md

Documentation hasn't been updated in three years and new functionality has been added since then.
This is the most important once since people might think that they can't perform merges on JSON yet.

Update documentation to include JSON merge example.

---

polymod/backends/PolymodAssetLibrary.hx

These video file types are commonly used for cutscenes, etc., and therefore should be included in the list of default extensions.

Add some video file types.

---

polymod/Polymod.hx

Previously the modMetadata wasn't being used for this error. This [issue ](https://github.com/larsiusprime/polymod/issues/59) should of been closed by now!

Fixed error not using correct Mod Metadata File

---

polymod/hscript/_internal/PolymodInterpEx.hx

It`s appears only when you using scripted functions, because PolymodInterpEx creates with null proxy.

Null object reference fix for scripted functions

---

polymod/hscript/_internal/PolymodParserEx.hx

Since [this](https://github.com/HaxeFoundation/hscript/commit/e5bef49bb6cbeb925c5b8f5d8fc40d118fda5177) commit on hscript repo, polymod fails to compile with it, this should fix it.

Fix for hscript above 2.5.0

---

polymod/hscript/_internal/HScriptedClassMacro.hx

Fixes the "Type not found : T" error
the issue was that `deparameterizeType` took `FlxTypedGroup.T` and returned `FlxTypedContainer.T` which,  in turn, needed to be deparameterized
I'm doing the same for TAbstract, which has no effect on my tests, but I thought I'd add it, I have no idea what you are doing with Abstract Params, I assume you're just looking for `MyScriptedClass<MyAbstract<T>>` and deparameterizing T, is that the case? do you have any other tests I should try?
Additionally, is there a way to code this that would make errors of this type more helpful? I'm looking at the fields created and they seem to have a valid pos, so no idea why the T error has no position

Recursively deparameterize TInst and TAbstract

---

polymod/hscript/_internal/PolymodScriptClass.hx

```haxe
// current output
"examplepackage.examplesubpackageExampleClass"
// fixed output
"examplepackage.examplesubpackage.ExampleClass"
```

fix get_className output

---

polymod/util/DefineUtil.hx

This fixes `getDefineBool` always returning `false` even if a default value was set.
Also makes every function only use either default or optional arguments instead of both at once.

[BUGFIX] Fix DefineUtil bool default value not working

---

polymod/hscript/_internal/PolymodAbstractScriptClass.hx
polymod/hscript/_internal/PolymodInterpEx.hx

Fixes https://github.com/FunkinCrew/Funkin/issues/3781
Doesn't have any other PR that has to be merged in order to work, hooray!!!
for getting the variable, the words supported are "get", "null" and everything else (i.e. "default")
for setting the variable, the words supported are "set", "never", "null" and everything else (i.e. "default")
also uhh haven't had the chance to test this *that* much so like if you want to uh test it yourself n stuff

[FEATURE] Support for `get` and `set` functions

---

polymod/hscript/_internal/PolymodInterpEx.hx

Related issue: https://github.com/FunkinCrew/Funkin/issues/3031
Test code:
```haxe
var a:String = null;
try {
trace(a.length);
}
catch (err:Dynamic) {
trace("Catched error: " + err);
}
```
Output:
```
hscriptClass(assets/test.hxc):20: Catched error: hscriptClass(assets/test.hxc):14: Invalid access to field length
```

Fix(?) try/catch

---

polymod/Polymod.hx
polymod/hscript/_internal/PolymodClassDeclEx.hx
polymod/hscript/_internal/PolymodEnum.hx
polymod/hscript/_internal/PolymodEnumDeclEx.hx
polymod/hscript/_internal/PolymodInterpEx.hx

This pr adds the ability to define enums in scripts, which will be stored in the `_scriptEnumDescriptor` map.
You can import enums from other scripts doing it the way in regular haxe, meaning:
```haxe
import my.enum.EnumName;
```
This pr requires this [pr](https://github.com/FunkinCrew/hscript/pull/5) to be merged.

[FEATURE] Enums

---

polymod/hscript/_internal/PolymodInterpEx.hx
polymod/hscript/_internal/PolymodScriptClass.hx

Fixes #231 
Fixes both bugs that are part of the linked issue: functions being called twice in certain occasions and variables being lost from being overwritten but never restored to their previous values.

[FIX] Fix the "most deranged context loss error of all time"

---

polymod/Polymod.hx
polymod/hscript/_internal/PolymodParserEx.hx
polymod/hscript/_internal/PolymodTyperEx.hx

Uses [hscript-typer](https://lib.haxe.org/p/hscript-typer/) to type modules. Currently we don't use the returned typed modules, however the typer is still useful for catching errors in scripts before running them.
(In the future if we use the typed modules, we could potentially manage to interpret overriden operators of abstracts, without the need to explicitly call the operator functions. But this would be on the back burner for a while.)

[FEATURE] Hscript Typer

---

polymod/hscript/_internal/PolymodAbstractScriptClass.hx
polymod/hscript/_internal/PolymodExprEx.hx
polymod/hscript/_internal/PolymodInterpEx.hx
polymod/hscript/_internal/PolymodPrinterEx.hx
polymod/hscript/_internal/PolymodScriptClass.hx

Improves support for properties so that they act more like Haxe ones.
* Accessing a property inside its get/set won't cause infinite recursion anymore.
* Properties with both a getter and a setter will act like they don't have a "physical field", so trying to access it inside them will yield an error, just like in Haxe. Adding `@:isVar` to the field will prevent this.
* Fixes postfix increment not acting like it should.

[ENHANCEMENT] Improve properties support

---

polymod/hscript/_internal/PolymodClassDeclEx.hx
polymod/hscript/_internal/PolymodInterpEx.hx
polymod/hscript/_internal/PolymodScriptClass.hx

Reopening of https://github.com/larsiusprime/polymod/pull/196 due to messy commit history. View that PR for more information.
Now it additionally caches functions of every `using` on init.
Still requires https://github.com/FunkinCrew/hscript/pull/7 to be merged alongside this.

[FEATURE] The `using` keyword

---

polymod/backends/HEAPSBackend.hx
polymod/backends/LimeBackend.hx
polymod/backends/PolymodAssetLibrary.hx
polymod/util/Util.hx

A previous pull request optimized the asset loading code, and with it introduced code where mod assets are redirected to the proper libraries based on the first folder in the path; however it failed to realize it was including the slash when comparing the library names, so for instance it would compare `shared/ == shared`, basically failing every time. This PR fixes that.
Aside from the minor adjustments, it will also now check if the path is in an `_append` or `_merge` folder, though it doesn't fix how other libraries are not being accounted for in the append/merge path, so given a file in `shared:someFile.txt`, appending will require the path to be `_append/someFile.txt` instead of `_append/shared/someFile.txt`. All usually mergeable/appendable files in FNF are in the `default` library …

[FIX] Fix mod assets always going into the `default` library
